services:
  api:
    build:
        context: .
        dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: run
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - ts-ddd
networks:
  ts-ddd:
volumes:
  node_modules:
